apiVersion: apps/v1
kind: Deployment
metadata:
  name: example-app
spec:
  replicas: 1
  template:
    metadata:
      labels: example-app
    spec:
      containers:
      - name: example-app
        image: nginx:1.14.2
        ports:
          - containerPort: 80
            name: http
            protocol: TCP