# Source: kestra/charts/minio/templates/secrets.yaml
apiVersion: v1
kind: Secret
metadata:
  name: kestra-minio
  namespace: "default"
  labels:
    app: minio
    chart: minio-4.1.0
    release: kestra
    heritage: Helm
type: Opaque
data:
  rootUser: "cGxlYXNlLWNoYW5nZS1tZQ=="
  rootPassword: "aXRzLW5vdC1hLXNlY3JldA=="
