# Source: kestra/charts/postgresql/templates/secrets.yaml
apiVersion: v1
kind: Secret
metadata:
  name: kestra-postgresql
  namespace: "default"
  labels:
    app.kubernetes.io/name: postgresql
    helm.sh/chart: postgresql-12.2.8
    app.kubernetes.io/instance: kestra
    app.kubernetes.io/managed-by: Helm
type: Opaque
data:
  postgres-password: "NXRhSVROanYyMg=="
  password: "a2VzdHJh"
  # We don't auto-generate LDAP password when it's not provided as we do for other passwords
