# Source: kestra/templates/service.yaml
apiVersion: v1
kind: Service
metadata:
  name: kestra-service
  labels:
    app.kubernetes.io/name: kestra
    app.kubernetes.io/component: service
    app.kubernetes.io/instance: kestra
    app.kubernetes.io/version: "0.17.0"
    app.kubernetes.io/managed-by: Helm
    helm.sh/chart: kestra-0.17.0
spec:
  type: ClusterIP
  ports:
  - port: 8080
    targetPort: http
    protocol: TCP
    name: http
    nodePort: 31260
  selector:
    app.kubernetes.io/name: kestra
    app.kubernetes.io/component: standalone
    app.kubernetes.io/instance: kestra
