# Source: kestra/charts/minio/templates/console-service.yaml
apiVersion: v1
kind: Service
metadata:
  name: kestra-minio-console
  namespace: "default"
  labels:
    app: minio
    chart: minio-4.1.0
    release: kestra
    heritage: Helm
spec:
  type: ClusterIP
  ports:
    - name: http
      port: 9001
      protocol: TCP
      targetPort: 9001
  selector:
    app: minio
    release: kestra
