# Source: kestra/charts/minio/templates/service.yaml
apiVersion: v1
kind: Service
metadata:
  name: kestra-minio
  namespace: "default"
  labels:
    app: minio
    chart: minio-4.1.0
    release: kestra
    heritage: Helm
    monitoring: "true"
spec:
  type: ClusterIP
  ports:
    - name: http
      port: 9000
      protocol: TCP
      targetPort: 9000
  selector:
    app: minio
    release: kestra
