apiVersion: v1
kind: Service
metadata:
  name: mssql
spec:
  selector:
    app: mssql
  externalIPs:
  - 192.168.0.25
  externalTrafficPolicy: Cluster
  internalTrafficPolicy: Cluster
  ipFamilies:
  - IPv4
  ipFamilyPolicy: SingleStack
  ports:
  - name: http
    port: 1433
    nodePort: 31350
    protocol: TCP
    targetPort: 1433
  sessionAffinity: None
  type: NodePort
