apiVersion: v1
kind: Service
metadata:
  name: grafana-dashboard
  namespace: grafana
spec:
  selector:
    app: grafana-dashboard
  externalIPs:
  - 192.168.0.25
  externalTrafficPolicy: Cluster
  internalTrafficPolicy: Cluster
  ipFamilies:
  - IPv4
  ipFamilyPolicy: SingleStack
  ports:
  - name: http
    port: 3000
    nodePort: 31299
    protocol: TCP
    targetPort: 3000
  sessionAffinity: None
  type: NodePort
