apiVersion: apps/v1
kind: Deployment
metadata:
  name: pihole
spec:
  replicas: 1
  selector:
    matchLabels:
      app: pihole
  template:
    metadata:
      labels:
        app: pihole
    spec:
      containers:
      - name: pihole
        image: pihole/pihole:latest
        ports:
        - containerPort: 80
        - containerPort: 53
        env:
        - name: TZ
          value: "Australia/Melbourne"
        - name: WEBPASSWORD
          value: "securestPasswordEver123!@#"
        resources:
          limits:
            memory: "500Mi"
            cpu: "500m"
        volumeMounts:
        - name: pihole-config
          mountPath: /etc/pihole
        - name: dnsmasq-config
          mountPath: /etc/dnsmasq.d
      volumes:
      - name: pihole-config
        emptyDir: {}
      - name: dnsmasq-config
        emptyDir: {}
