apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pihole-pvc
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 500M # Adjust based on your needs
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: dnsmasq-pvc
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 500M # Adjust based on your needs
