apiVersion: v1
kind: Service
metadata:
  name: pihole
  labels:
    app: pihole
spec:
  type: NodePort
  ports:
  - port: 80
    targetPort: 80
    nodePort: 30080 # Specify the node port you want
  - port: 53
    protocol: UDP
    targetPort: 53
    nodePort: 30053 # Specify the node port for UDP
  selector:
    app: pihole
