apiVersion: v1
kind: Service
metadata:
  name: postgres-service
spec:
  selector:
    app: postgres
  externalIPs:
  - 192.168.0.103
  externalTrafficPolicy: Cluster
  internalTrafficPolicy: Cluster
  ipFamilies:
  - IPv4
  ipFamilyPolicy: SingleStack
  ports:
  - protocol: TCP
    port: 5432
    nodePort: 31350
    targetPort: 5432
  sessionAffinity: None
  type: NodePort
